name: Bug Report
description: Report a bug or issue with Notepad++ MCP Server
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: input
    id: version
    attributes:
      label: MCP Server Version
      description: What version of notepadpp-mcp are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you running?
      options:
        - Windows 10
        - Windows 11
        - Windows Server 2019+
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: e.g., Python 3.11.5
    validations:
      required: true

  - type: input
    id: notepadpp-version
    attributes:
      label: Notepad++ Version
      description: What version of Notepad++ are you using?
      placeholder: e.g., Notepad++ 8.5.4
    validations:
      required: true

  - type: dropdown
    id: client
    attributes:
      label: MCP Client
      description: Which MCP client are you using?
      options:
        - Claude Desktop
        - Other MCP client (please specify)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: A clear and concise description of what you expected to happen.

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: A clear and concise description of what actually happened.

  - type: textarea
    id: logs
    attributes:
      label: Logs/Screenshots
      description: Add any relevant logs, error messages, or screenshots
      placeholder: |
        If applicable, add logs or screenshots to help explain your problem.
        You can paste logs directly here or attach files.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful
