"""Generate additional MCPB examples to reach the 100+ 3-4-100 gate."""

import json
from pathlib import Path

base = Path(__file__).resolve().parents[1] / "assets" / "prompts" / "examples.json"
data = json.loads(base.read_text(encoding="utf-8"))
existing = data["examples"]

new = [
    # file_ops
    {
        "title": "Open File By Absolute Path",
        "description": "Open a file using its full path",
        "user_input": "Open C:/Projects/app/main.py",
        "tool_call": "file_ops",
        "parameters": {"operation": "open", "file_path": "C:/Projects/app/main.py"},
        "expected_output": "File opened: main.py",
    },
    {
        "title": "Create Scratch Buffer",
        "description": "Start a fresh untitled buffer",
        "user_input": "Give me a new empty tab",
        "tool_call": "file_ops",
        "parameters": {"operation": "new"},
        "expected_output": "New buffer created",
    },
    {
        "title": "Save With Path",
        "description": "Save the buffer to a specific path",
        "user_input": "Save this as D:/tmp/notes.md",
        "tool_call": "file_ops",
        "parameters": {"operation": "save", "file_path": "D:/tmp/notes.md"},
        "expected_output": "File saved: notes.md",
    },
    {
        "title": "Inspect Active File",
        "description": "Get metadata for the active document",
        "user_input": "What file is open right now?",
        "tool_call": "file_ops",
        "parameters": {"operation": "info"},
        "expected_output": "Active file info returned",
    },
    {
        "title": "Open Relative Project File",
        "description": "Open a file relative to the project",
        "user_input": "open src/utils.py for me",
        "tool_call": "file_ops",
        "parameters": {"operation": "open", "file_path": "src/utils.py"},
        "expected_output": "File opened: utils.py",
    },
    {
        "title": "Save All Open Changes",
        "description": "Persist the active buffer",
        "user_input": "save my changes please",
        "tool_call": "file_ops",
        "parameters": {"operation": "save"},
        "expected_output": "File saved successfully",
    },
    {
        "title": "Create New Config Buffer",
        "description": "Create a new buffer for config work",
        "user_input": "new file for a config",
        "tool_call": "file_ops",
        "parameters": {"operation": "new"},
        "expected_output": "New buffer created",
    },
    # text_ops
    {
        "title": "Insert Text At Caret",
        "description": "Insert text at the current cursor position",
        "user_input": "insert the word TODO here",
        "tool_call": "text_ops",
        "parameters": {"operation": "insert", "text": "TODO"},
        "expected_output": "Text inserted",
    },
    {
        "title": "Insert Multi-line Snippet",
        "description": "Insert a code snippet with newlines",
        "user_input": "add a license header block",
        "tool_call": "text_ops",
        "parameters": {"operation": "insert", "text": "# Copyright 2026\n# MIT License"},
        "expected_output": "Text inserted",
    },
    {
        "title": "Find Keyword Case Sensitive",
        "description": "Find a keyword with exact casing",
        "user_input": "find 'Error' exactly",
        "tool_call": "text_ops",
        "parameters": {"operation": "find", "text": "Error", "case_sensitive": True},
        "expected_output": "Match found",
    },
    {
        "title": "Find Keyword Ignoring Case",
        "description": "Find a keyword case-insensitively",
        "user_input": "search for 'error' anywhere",
        "tool_call": "text_ops",
        "parameters": {"operation": "find", "text": "error", "case_sensitive": False},
        "expected_output": "Match found",
    },
    {
        "title": "Find And Report Count",
        "description": "Find a word and get the occurrence count",
        "user_input": "how many times does 'def' appear",
        "tool_call": "text_ops",
        "parameters": {"operation": "find", "text": "def"},
        "expected_output": "Occurrences reported",
    },
    {
        "title": "Insert Current Date",
        "description": "Insert a timestamp at the caret",
        "user_input": "insert today's date",
        "tool_call": "text_ops",
        "parameters": {"operation": "insert", "text": "2026-08-03"},
        "expected_output": "Text inserted",
    },
    # tab_ops
    {
        "title": "List All Open Tabs",
        "description": "Enumerate every open editor tab",
        "user_input": "show me all open tabs",
        "tool_call": "tab_ops",
        "parameters": {"operation": "list"},
        "expected_output": "Tabs listed with indices",
    },
    {
        "title": "Switch To First Tab",
        "description": "Activate the first tab",
        "user_input": "go to the first tab",
        "tool_call": "tab_ops",
        "parameters": {"operation": "switch", "tab_index": 0},
        "expected_output": "Switched to tab 0",
    },
    {
        "title": "Switch To Tab By Index",
        "description": "Activate a specific tab by index",
        "user_input": "switch to tab 3",
        "tool_call": "tab_ops",
        "parameters": {"operation": "switch", "tab_index": 3},
        "expected_output": "Switched to tab 3",
    },
    {
        "title": "Close Active Tab",
        "description": "Close the current tab",
        "user_input": "close this tab",
        "tool_call": "tab_ops",
        "parameters": {"operation": "close"},
        "expected_output": "Active tab closed",
    },
    {
        "title": "Close Tab By Index",
        "description": "Close a specific tab",
        "user_input": "close tab 2",
        "tool_call": "tab_ops",
        "parameters": {"operation": "close", "tab_index": 2},
        "expected_output": "Tab 2 closed",
    },
    {
        "title": "Close All But Current",
        "description": "Close other tabs via list+close",
        "user_input": "close every tab except this one",
        "tool_call": "tab_ops",
        "parameters": {"operation": "close", "tab_index": -1},
        "expected_output": "Current tab preserved, others closed",
    },
    # session_ops
    {
        "title": "Save Workspace Session",
        "description": "Persist the current workspace as a named session",
        "user_input": "save my current workspace as 'project-x'",
        "tool_call": "session_ops",
        "parameters": {"operation": "save", "session_name": "project-x"},
        "expected_output": "Session saved: project-x.xml",
    },
    {
        "title": "List Saved Sessions",
        "description": "Show all persisted sessions",
        "user_input": "which sessions do I have",
        "tool_call": "session_ops",
        "parameters": {"operation": "list"},
        "expected_output": "Sessions listed",
    },
    {
        "title": "Load Saved Session",
        "description": "Restore a named session",
        "user_input": "reopen yesterday's session 'morning'",
        "tool_call": "session_ops",
        "parameters": {"operation": "load", "session_name": "morning"},
        "expected_output": "Session loaded: morning.xml",
    },
    {
        "title": "Save Daily Session",
        "description": "Snapshot the workspace before shutdown",
        "user_input": "save everything before I close",
        "tool_call": "session_ops",
        "parameters": {"operation": "save", "session_name": "daily-2026-08-03"},
        "expected_output": "Session saved",
    },
    {
        "title": "Resume Interrupted Work",
        "description": "Reload a session after a crash",
        "user_input": "restore my 'research' session",
        "tool_call": "session_ops",
        "parameters": {"operation": "load", "session_name": "research"},
        "expected_output": "Session loaded: research.xml",
    },
    # linting_ops
    {
        "title": "Lint Python File",
        "description": "Run Python linting on a file",
        "user_input": "check this python file for issues",
        "tool_call": "linting_ops",
        "parameters": {"operation": "python", "file_path": "C:/tmp/script.py"},
        "expected_output": "Lint issues reported",
    },
    {
        "title": "Lint JavaScript File",
        "description": "Run ESLint-style checks",
        "user_input": "lint my app.js",
        "tool_call": "linting_ops",
        "parameters": {"operation": "javascript", "file_path": "C:/tmp/app.js"},
        "expected_output": "Lint issues reported",
    },
    {
        "title": "Validate JSON File",
        "description": "Validate JSON syntax",
        "user_input": "is my config.json valid",
        "tool_call": "linting_ops",
        "parameters": {"operation": "json", "file_path": "C:/tmp/config.json"},
        "expected_output": "JSON validation result",
    },
    {
        "title": "Check Markdown File",
        "description": "Check markdown structure",
        "user_input": "check the README formatting",
        "tool_call": "linting_ops",
        "parameters": {"operation": "markdown", "file_path": "C:/tmp/README.md"},
        "expected_output": "Markdown issues reported",
    },
    {
        "title": "List Lint Engines",
        "description": "Show available lint backends",
        "user_input": "what linters are available",
        "tool_call": "linting_ops",
        "parameters": {"operation": "tools"},
        "expected_output": "Linting tools listed",
    },
    {
        "title": "Lint Python With Ruff",
        "description": "Lint a python file using ruff",
        "user_input": "run ruff on my code",
        "tool_call": "linting_ops",
        "parameters": {"operation": "python", "file_path": "C:/dev/module.py"},
        "expected_output": "Ruff issues reported",
    },
    {
        "title": "Lint JavaScript With ESLint",
        "description": "Direct ESLint tool call",
        "user_input": "eslint this file",
        "tool_call": "lint_javascript_file",
        "parameters": {"file_path": "C:/dev/main.js"},
        "expected_output": "ESLint JSON output",
    },
    {
        "title": "Validate JSON Direct",
        "description": "Direct JSON validation tool call",
        "user_input": "validate package.json",
        "tool_call": "lint_json_file",
        "parameters": {"file_path": "C:/dev/package.json"},
        "expected_output": "JSON validation result",
    },
    {
        "title": "Check Markdown Direct",
        "description": "Direct markdown check tool call",
        "user_input": "check this doc",
        "tool_call": "lint_markdown_file",
        "parameters": {"file_path": "C:/dev/CHANGELOG.md"},
        "expected_output": "Markdown issues reported",
    },
    # display_ops
    {
        "title": "Fix Invisible Text",
        "description": "Repair invisible/blank text rendering",
        "user_input": "the text is invisible, fix it",
        "tool_call": "display_ops",
        "parameters": {"operation": "fix_invisible_text"},
        "expected_output": "Display fixed",
    },
    {
        "title": "Fix General Display Issue",
        "description": "Broader redraw/refresh fix",
        "user_input": "the editor looks glitchy, refresh it",
        "tool_call": "display_ops",
        "parameters": {"operation": "fix_display_issue"},
        "expected_output": "Display refreshed",
    },
    {
        "title": "Check Theme Status",
        "description": "Read current theme configuration",
        "user_input": "what theme is active",
        "tool_call": "display_ops",
        "parameters": {"operation": "theme_status"},
        "expected_output": "Theme status returned",
    },
    {
        "title": "Enable Dark Mode",
        "description": "Turn on dark mode",
        "user_input": "switch to dark mode",
        "tool_call": "display_ops",
        "parameters": {"operation": "set_dark_mode", "dark_mode": True},
        "expected_output": "Dark mode enabled",
    },
    {
        "title": "Disable Dark Mode",
        "description": "Turn off dark mode",
        "user_input": "switch to light mode",
        "tool_call": "display_ops",
        "parameters": {"operation": "set_dark_mode", "dark_mode": False},
        "expected_output": "Dark mode disabled",
    },
    {
        "title": "Set Editor Theme",
        "description": "Apply a theme XML",
        "user_input": "apply the Solarized theme",
        "tool_call": "display_ops",
        "parameters": {"operation": "set_editor_theme", "theme_xml": "Solarized.xml"},
        "expected_output": "Theme applied: Solarized.xml",
    },
    # plugin_ops
    {
        "title": "Discover XML Plugins",
        "description": "Search the official plugin list",
        "user_input": "find XML plugins",
        "tool_call": "plugin_ops",
        "parameters": {"operation": "discover", "search_term": "xml", "limit": 10},
        "expected_output": "Plugins found: 10",
    },
    {
        "title": "Discover By Category",
        "description": "Filter plugins by category",
        "user_input": "list source control plugins",
        "tool_call": "plugin_ops",
        "parameters": {"operation": "discover", "category": "Source Control", "limit": 20},
        "expected_output": "Plugins found",
    },
    {
        "title": "Install Plugin",
        "description": "Install a named plugin",
        "user_input": "install XMLTools",
        "tool_call": "plugin_ops",
        "parameters": {"operation": "install", "plugin_name": "XMLTools"},
        "expected_output": "Install initiated",
    },
    {
        "title": "List Installed Plugins",
        "description": "Show installed plugin DLLs",
        "user_input": "what plugins do I have installed",
        "tool_call": "plugin_ops",
        "parameters": {"operation": "list"},
        "expected_output": "Installed plugins listed",
    },
    {
        "title": "Execute Plugin Command",
        "description": "Run a plugin command",
        "user_input": "run the format command in XMLTools",
        "tool_call": "plugin_ops",
        "parameters": {"operation": "execute", "plugin_name": "XMLTools", "command": "format"},
        "expected_output": "Plugin command executed",
    },
    {
        "title": "Discover Hex Editor Plugins",
        "description": "Search for hex editor tools",
        "user_input": "is there a hex editor plugin",
        "tool_call": "plugin_ops",
        "parameters": {"operation": "discover", "search_term": "hex", "limit": 5},
        "expected_output": "Plugins found",
    },
    # status_ops
    {
        "title": "Run Health Check",
        "description": "Verify Notepad++ connectivity",
        "user_input": "is the editor reachable",
        "tool_call": "status_ops",
        "parameters": {"operation": "health_check"},
        "expected_output": "Health check passed",
    },
    {
        "title": "Get System Status",
        "description": "Server and config snapshot",
        "user_input": "show server status",
        "tool_call": "status_ops",
        "parameters": {"operation": "system_status"},
        "expected_output": "System status returned",
    },
    {
        "title": "Get File Ops Help",
        "description": "Scoped help for file operations",
        "user_input": "how do I use file_ops",
        "tool_call": "status_ops",
        "parameters": {"operation": "help", "category": "file_operations"},
        "expected_output": "Help for file_operations",
    },
    {
        "title": "Get Plugin Help",
        "description": "Scoped help for plugin operations",
        "user_input": "explain plugin_ops",
        "tool_call": "status_ops",
        "parameters": {"operation": "help", "category": "plugin_operations", "tool_name": "plugin_ops"},
        "expected_output": "Help for plugin_ops",
    },
    {
        "title": "Health Check After Install",
        "description": "Verify editor after setup",
        "user_input": "verify the editor works after install",
        "tool_call": "status_ops",
        "parameters": {"operation": "health_check"},
        "expected_output": "Health check passed",
    },
    # meta tools
    {
        "title": "Show Dashboard Card",
        "description": "Render the Prefab dashboard",
        "user_input": "show me the dashboard",
        "tool_call": "notepad_dashboard",
        "parameters": {},
        "expected_output": "Dashboard rendered",
    },
    {
        "title": "Suggest Editing Plan",
        "description": "Sampling-based plan",
        "user_input": "plan how to refactor this file",
        "tool_call": "suggest_notepad_plan",
        "parameters": {"goal": "Refactor the active Python file into functions"},
        "expected_output": "Step-by-step plan",
    },
    {
        "title": "Agentic Workflow",
        "description": "Multi-step sampled workflow",
        "user_input": "open my project and lint all python files",
        "tool_call": "agentic_notepad_workflow",
        "parameters": {
            "workflow_prompt": "Open the project directory and lint every python file",
            "available_tools": ["file_ops", "linting_ops"],
            "max_iterations": 10,
        },
        "expected_output": "Workflow results",
    },
    {
        "title": "Shutdown Server",
        "description": "Graceful bridge shutdown",
        "user_input": "stop the server",
        "tool_call": "notepadpp_shutdown",
        "parameters": {"confirm": True},
        "expected_output": "Bridge shutting down",
    },
    # multi-step combo examples
    {
        "title": "Open Then Insert Header",
        "description": "Open a file and insert a header",
        "user_input": "open notes.md and add a title",
        "tool_call": "file_ops",
        "parameters": {"operation": "open", "file_path": "C:/tmp/notes.md"},
        "expected_output": "File opened; follow with text_ops insert",
    },
    {
        "title": "Find Then Insert",
        "description": "Locate a marker and insert after it",
        "user_input": "find the TODO marker and add a note below",
        "tool_call": "text_ops",
        "parameters": {"operation": "find", "text": "TODO"},
        "expected_output": "Marker found; follow with text_ops insert",
    },
    {
        "title": "Lint Then Fix",
        "description": "Lint and prepare fixes",
        "user_input": "lint my script and tell me what to fix",
        "tool_call": "linting_ops",
        "parameters": {"operation": "python", "file_path": "C:/tmp/script.py"},
        "expected_output": "Issues listed for fixing",
    },
    {
        "title": "Session Save Before Quit",
        "description": "Persist state before closing",
        "user_input": "save session and close",
        "tool_call": "session_ops",
        "parameters": {"operation": "save", "session_name": "final"},
        "expected_output": "Session saved; follow with tab_ops close",
    },
    {
        "title": "Install Then List",
        "description": "Install a plugin and verify",
        "user_input": "install JSONTools and confirm",
        "tool_call": "plugin_ops",
        "parameters": {"operation": "install", "plugin_name": "JSONTools"},
        "expected_output": "Install initiated; follow with plugin_ops list",
    },
    {
        "title": "Theme Check Then Set",
        "description": "Inspect and change theme",
        "user_input": "check my theme and make it dark",
        "tool_call": "display_ops",
        "parameters": {"operation": "theme_status"},
        "expected_output": "Theme status; follow with set_dark_mode",
    },
    {
        "title": "Switch Tab Then Edit",
        "description": "Navigate and edit",
        "user_input": "switch to the config tab and add a key",
        "tool_call": "tab_ops",
        "parameters": {"operation": "switch", "tab_index": 1},
        "expected_output": "Switched; follow with text_ops insert",
    },
    {
        "title": "Health Check Then Lint",
        "description": "Verify editor before linting",
        "user_input": "make sure the editor is up, then lint",
        "tool_call": "status_ops",
        "parameters": {"operation": "health_check"},
        "expected_output": "Healthy; follow with linting_ops",
    },
    {
        "title": "Open Project Then Session",
        "description": "Open files and snapshot workspace",
        "user_input": "open the project and save the workspace",
        "tool_call": "file_ops",
        "parameters": {"operation": "open", "file_path": "C:/Projects/app/main.py"},
        "expected_output": "Opened; follow with session_ops save",
    },
    {
        "title": "Discover Then Execute",
        "description": "Discover a plugin and use it",
        "user_input": "find a compare plugin and run it",
        "tool_call": "plugin_ops",
        "parameters": {"operation": "discover", "search_term": "compare", "limit": 5},
        "expected_output": "Plugin found; follow with plugin_ops execute",
    },
]

existing_ids = {(e["tool_call"], e["parameters"].get("operation", ""), e["title"]) for e in existing}
merged = list(existing)
for e in new:
    key = (e["tool_call"], e["parameters"].get("operation", ""), e["title"])
    if key not in existing_ids:
        merged.append(e)
        existing_ids.add(key)

data["examples"] = merged
base.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"examples: {len(existing)} -> {len(merged)}")
